/**
 * Pure storage helpers for the local adapter, isolated from the DOM/BroadcastChannel wiring so they
 * can be unit-tested against a plain in-memory `Storage` double.
 *
 * The store is **one key per participant** — `mp:<sessionId>:<participantId>` — never a single shared
 * blob. `localStorage` has no transactions, so a shared blob has a read-modify-write race: two tabs
 * read it, each mutates its own slice, and the second write clobbers the first (with no version to
 * detect the conflict). Per-participant keys sidestep that entirely — a tab only ever writes its own
 * key — and reproduce the JATOS adapter's REPLACE-the-whole-slot semantics exactly, so plugins can't
 * behave differently between the two adapters.
 */

import { GroupSessionData } from "./multiplayer-adapter";

/** The minimal slice of the Web Storage API this module needs (a subset of `Storage`). */
export interface SlotStorage {
  readonly length: number;
  key(index: number): string | null;
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
  removeItem(key: string): void;
}

/** Prefix shared by every key belonging to one session: `mp:<sessionId>:`. */
export function slotPrefix(keyPrefix: string, sessionId: string): string {
  return `${keyPrefix}:${sessionId}:`;
}

/** Full storage key for one participant's slot. */
export function slotKey(keyPrefix: string, sessionId: string, participantId: string): string {
  return slotPrefix(keyPrefix, sessionId) + participantId;
}

/**
 * The participantId encoded in a storage key, or `null` if the key doesn't belong to this session.
 * A participantId never contains the prefix's `:` boundary because it's generated by `generateId`,
 * so a single `startsWith` + slice is unambiguous.
 */
export function participantIdFromKey(
  keyPrefix: string,
  sessionId: string,
  key: string
): string | null {
  const prefix = slotPrefix(keyPrefix, sessionId);
  return key.startsWith(prefix) ? key.slice(prefix.length) : null;
}

/** Read and JSON-parse one participant's slot; `undefined` if absent or unparseable. */
export function readSlot(
  storage: SlotStorage,
  keyPrefix: string,
  sessionId: string,
  participantId: string
): Record<string, unknown> | undefined {
  const raw = storage.getItem(slotKey(keyPrefix, sessionId, participantId));
  if (raw === null) return undefined;
  try {
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    // A slot corrupted by hand-editing shouldn't crash the whole snapshot read.
    return undefined;
  }
}

/** Enumerate every slot in this session into a `participantId -> data` snapshot. */
export function readAllSlots(
  storage: SlotStorage,
  keyPrefix: string,
  sessionId: string
): GroupSessionData {
  const all: GroupSessionData = {};
  // Snapshot the keys first: reading is side-effect-free, but iterating by live index while the
  // store could change underneath is fragile, and the key set is tiny (one per participant).
  const keys: string[] = [];
  for (let i = 0; i < storage.length; i++) {
    const key = storage.key(i);
    if (key !== null) keys.push(key);
  }
  for (const key of keys) {
    const id = participantIdFromKey(keyPrefix, sessionId, key);
    if (id === null) continue;
    const raw = storage.getItem(key);
    if (raw === null) continue;
    try {
      all[id] = JSON.parse(raw) as Record<string, unknown>;
    } catch {
      // Skip a corrupted slot rather than failing the whole enumeration.
    }
  }
  return all;
}

/** Write (REPLACE) one participant's slot. */
export function writeSlot(
  storage: SlotStorage,
  keyPrefix: string,
  sessionId: string,
  participantId: string,
  data: Record<string, unknown>
): void {
  storage.setItem(slotKey(keyPrefix, sessionId, participantId), JSON.stringify(data));
}

/** Remove one participant's slot (used on disconnect so a closed tab doesn't linger as a ghost). */
export function removeSlot(
  storage: SlotStorage,
  keyPrefix: string,
  sessionId: string,
  participantId: string
): void {
  storage.removeItem(slotKey(keyPrefix, sessionId, participantId));
}

/**
 * A random, collision-free identifier. Used for both the per-tab participantId and an auto-generated
 * sessionId. Deliberately NOT an ordinal like "player-1": two tabs racing to claim an ordinal via
 * read-then-write is the exact race the per-key store is built to avoid, and it has no lock-free
 * answer. No plugin orders by the id's value — `plugin-multiplayer-role` orders by each participant's
 * pushed `joinedAt` (tie-broken by a code-unit compare only for determinism) — so random ids give
 * stable, coordination-free role/turn assignment.
 */
export function generateId(): string {
  const cryptoObj = typeof globalThis !== "undefined" ? globalThis.crypto : undefined;
  if (cryptoObj && typeof cryptoObj.randomUUID === "function") {
    return cryptoObj.randomUUID();
  }
  // Fallback for older/embedded runtimes without crypto.randomUUID.
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}
